### PR TITLE
[DASH-2187] Fix clearing channel message text

### PR DESCRIPTION
**Pull request by wpasinski**
I also made some minor visual changes (one "New message" section):

send message to sample-channel channel

### CODE REVIEW

**Comment by wpasinski** [comment]
can anyone confirm Marcin's issue (video in JIRA task comments)?

**Comment by Flixow** [comment]
For me it works properly

**Comment by gh3r** [comment]
@wpasinski Still i get kicked out of the instance

**Comment by wpasinski** [comment]
@gh3r There is an scenario when fetching channel history fails. I created DASH-2327 for this since it's not directly connected with current task.

**Pull request merged**
