### PR TITLE
[DASH-2339] Change Hosting into a Core Serivce

### PR DESCRIPTION
**Pull request by tomsonpl**
screen shot 2016-10-27 at 15 43 30
screen shot 2016-10-27 at 15 43 40
screen shot 2016-10-27 at 15 43 48

### CODE REVIEW

**Comment by wpasinski** [comment]
we should also change _Go Back to Hosting Sockets_ text.

**Comment by wpasinski** [comment]
and I'm still a big fan of the following concept:

zrzut ekranu 2016-10-12 o 21 45 53

**Comment by tomsonpl** [comment]
@wpasinski  you mean moving Hosting to the very bottom? and hiding the sub sections?

**Comment by tomsonpl** [comment]
@wpasinski  I think that your version makes sense. But wouldn't it be a better idea to wait until thursday and have a long discussion over it on Features meeting and then decide?

**Comment by wpasinski** [comment]
@tomsonpl It would. It's just an idea and I want to know what others think about it.

**Comment by tomsonpl** [comment]
you have my sword, vote: +1

**Comment by Flixow** [comment]
We've moved _Hosting_ from _Sockets_ section, so I have no idea why you want to change text to _Hosting Sockets_. Maybe _Go Back to all Hostings_ or something like this but on my mind nothing linked with _Socket_. And I also support the idea with move Hosting to the bottom of the list.

**Comment by wpasinski** [comment]
@Flixow my ss is only about the sidebar. I just did a fast change in code to show that.

**Comment by Flixow** [comment]
So, let's discuss about it later, and now LGTM

**Comment by tomsonpl** [comment]
@gh3r not my fault, and not this task. It is this way on rocks. Sorry for wrong DASH number ;p

**Comment by gh3r** [comment]
LGTM

**Comment by Flixow** [comment]
Display does not work which hosting is set as default.
image

**Comment by patrykkopycinski** [comment]
@Flixow it's fixed already

**Pull request merged**
