### PR TITLE
[DASH-2296] Remove 'set as default' 

### PR DESCRIPTION
**Pull request by tomsonpl**
screen shot 2016-10-13 at 10 49 02
screen shot 2016-10-13 at 11 21 12

Please let me know what do you think of it, anythink bigger, smaller, different?

### CODE REVIEW

**Comment by tomsonpl** [comment]
is `release files to your default hosting` good?

**Comment by wpasinski** [comment]
for me we can remove this toggle for every edit dialog. I don't see any problem with having this setting only in "dots dropdown". at least for now. but it's only my opinion and let's see how others see that issue.

**Comment by Flixow** [comment]
On my mind it makes sense in add Dialog, but not necessarily while user edit hosting. On the other hand our dialogs usually looks same in edit and add mode. Any others opinions?

**Comment by tomsonpl** [comment]
anybody else would like to comment on this? ;)

**Comment by patrykkopycinski** [comment]
@wpasinski you're responsible for the Hosting, should we remove that completely?

**Comment by wpasinski** [comment]
it's simply not the best context to ask user for default hosting. first one should be set automatically, and when there is a need to change that, we should be able to do that from view of all hosting to have clear view which hosting do we really want to be default.

i'm thinking of moving hosting out of sockets (is it "api builder"? not at all) and create something like "general hosting setting" with a dropdown setting for default one.

so yes, for me we can remove this toggle from all edit and create dialogs.

**Comment by mkucharz** [comment]
@wpasinski can you make some simple sketch with suggestion how it could be done?

**Comment by wpasinski** [comment]
@mkucharz I can try.

**Comment by patrykkopycinski** [comment]
@tomsonpl in the mean time
- remove "X" from the blue box
- reduce bottom margin of blue box (toggle should seems connected to this box, now it's not)
- change label, because now i think it's misleading, as you don't release files anywhere, files are going to stay where they are now, explanation in a blue box is fine, label should be: "Set as default hosting"

**Pull request merged**
