### PR TITLE
[DASH-2365] Add pagination for Data Objects

### PR DESCRIPTION
**Pull request by wpasinski**
zrzut ekranu 2016-11-28 o 20 40 02
zrzut ekranu 2016-11-28 o 20 40 12
zrzut ekranu 2016-11-28 o 20 40 21

### CODE REVIEW

**Comment by gh3r** [comment]
Also, we don't want to display all items that gonna be deleted? Only the count?

**Comment by wpasinski** [comment]
@gh3r Two things here:

1. I don't find invisible vertical scroll a bug. That's how it's implemented in Mac OS (see Finder app for example). Also it depends on user system preferences. It can look for example like this:

zrzut ekranu 2016-12-08 o 00 25 36

2. 

> Also, we don't want to display all items that gonna be deleted? Only the count?

That works for me. Any suggestions?

**Comment by gh3r** [comment]
@wpasinski As mentioned in task, we should display information about DO being delete, for example ID, it's a lot better than just number of them.

**Comment by wpasinski** [comment]
@gh3r Is this one ok?

zrzut ekranu 2016-12-08 o 16 56 25

**Comment by gh3r** [comment]
@wpasinski Yes, looks good 💪

**Comment by gh3r** [comment]
@patrykkopycinski ?

**Pull request merged**
