### PR TITLE
[DASH-2378] Change global config to readonly

### PR DESCRIPTION
**Pull request by wpasinski**
- are we sure we really want to comment out all these changes?
- should I comment out actions too?

### CODE REVIEW

**Comment by patrykkopycinski** [comment]
i think it's good to go, we can do it later

**Comment by gh3r** [comment]
@patrykkopycinski did we create task for it? If not please do, as we will forget about it.

**Comment by patrykkopycinski** [comment]
the question is if we want to have it

**Comment by gh3r** [comment]
Yes, we want, read-only editor view is misleading for me. First impression for user will be that he can do something with it.

**Comment by patrykkopycinski** [comment]
Just beacause you want it doesn't mean everybody wants ;P

**Pull request merged**
